-------------------------Run Single Time only----------
GO
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Menu_Parent]') AND parent_object_id = OBJECT_ID(N'[dbo].[Menu]'))
  BEGIN
   ALTER TABLE [dbo].[Menu] DROP CONSTRAINT FK_Menu_Parent;
  END
  IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_MenuPermission_Menu]') AND parent_object_id = OBJECT_ID(N'[dbo].[MenuPermission]'))
  BEGIN
  ALTER TABLE [dbo].[MenuPermission] DROP CONSTRAINT FK_MenuPermission_Menu;
  END
  IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_MenuPermission_Permission]') AND parent_object_id = OBJECT_ID(N'[dbo].[MenuPermission]'))
  BEGIN
  ALTER TABLE [dbo].[MenuPermission] DROP CONSTRAINT FK_MenuPermission_Permission;
  END
Truncate Table [dbo].[Menu]
SET IDENTITY_INSERT [dbo].[Menu] ON
 
INSERT INTO [dbo].[Menu]([Id],[Name],[ApiEndPoint],[ParentMenuId],[CreatedBy],[CreatedOn],[IsDeleted])
Values(1,'Employees','/api/EmployeeGroup/GetAllEmployees',null,'admin',Getdate(),0),
      (2,'Roles','/api/RolePermission/GetRoles',null,'admin',Getdate(),0),
	  (3,'Settings',null,null,'admin',Getdate(),0),
	  (4,'Employee Group','/api/EmployeeGroup/GetEmployeeGroupList',null,'admin',Getdate(),0),
	  (5,'Survey',null,null,'admin',Getdate(),0),
	  (6,'Events','/api/',null,'admin',Getdate(),0), 
	  (7,'Company Policy','/api/CompanyPolicy/GetCompanyPolicies',null,'admin',Getdate(),0),
	  (8,'Survey Report',null,5,'admin',Getdate(),0),
	  (9,'My surveys',null,5,'admin',Getdate(),0),
	  --(10,'Email and Notification','/api/',3,'admin',Getdate(),0),
	  (11,'Department','/api/',3,'admin',Getdate(),0),
	  (12,'Team','/api/',3,'admin',Getdate(),0),
	  (13,'Designation','/api/',3,'admin',Getdate(),0),
	  (14,'Attendance','null',null,'admin',Getdate(),0),
	  (15,'Attendance Report','/api/',14,'admin',Getdate(),0),
	  (16,'Attendance Configuration','/api/',14,'admin',Getdate(),0),
	  (17,'Employee Attendance Report','/api/',14,'admin',Getdate(),0),
	    (18,'Employees List','/api/',1,'admin',Getdate(),0),
	   (19,'Employee Exit','/api/',1,'admin',Getdate(),0)
  SET IDENTITY_INSERT [dbo].[Menu] OFF
 
 
   Truncate Table [dbo].[MenuPermission]
   SET IDENTITY_INSERT [dbo].[MenuPermission] ON
  INSERT INTO [dbo].[MenuPermission]([Id],[MenuId],[ReadPermissionId],[CreatedBy],[CreatedOn])
  Values (1,1,1,'admin',Getdate()),
       (2,2,26,'admin',Getdate()),
	   (3,3,31,'admin',Getdate()),
	   (4,4,36,'admin',Getdate()),
	   (5,5,61,'admin',Getdate()),
	   (6,6,51,'admin',Getdate()),
	   (7,7,56,'admin',Getdate()),
	   (8,8,61,'admin',Getdate()),
	   (9,9,61,'admin',Getdate()),
	   --(10,10,31,'admin',Getdate()),
	   (11,11,3,'admin',Getdate()),
	   (12,12,3,'admin',Getdate()),
	   (13,13,3,'admin',Getdate()),
	   (14,14,87,'admin',Getdate()),
	   (18,18,1,'admin',Getdate()),
	   (19,19,1,'admin',Getdate()) 
	 
  SET IDENTITY_INSERT [dbo].[MenuPermission] OFF
 
    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Menu_Parent]') AND parent_object_id = OBJECT_ID(N'[dbo].[Menu]'))
  BEGIN
   ALTER TABLE [dbo].[Menu]  WITH CHECK ADD  CONSTRAINT [FK_Menu_Parent] FOREIGN KEY(ParentMenuId) REFERENCES [Menu](Id)
  END
  IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_MenuPermission_Menu]') AND parent_object_id = OBJECT_ID(N'[dbo].[MenuPermission]'))
  BEGIN
   ALTER TABLE [dbo].[MenuPermission]  WITH CHECK ADD  CONSTRAINT [FK_MenuPermission_Menu]FOREIGN KEY(MenuId) REFERENCES [Menu](Id)
  END
    IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_MenuPermission_Permission]') AND parent_object_id = OBJECT_ID(N'[dbo].[MenuPermission]'))
  BEGIN
   ALTER TABLE [dbo].[MenuPermission]  WITH CHECK ADD  CONSTRAINT [FK_MenuPermission_Permission]FOREIGN KEY(ReadPermissionId) REFERENCES [Permission](Id)
  END
  IF Not EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Permission_Module]') AND parent_object_id = OBJECT_ID(N'[dbo].[Permission]'))
  ALTER TABLE [dbo].[Permission]  WITH CHECK ADD  CONSTRAINT [FK_Permission_Module] FOREIGN KEY([ModuleId])	REFERENCES [dbo].[Module] ([Id])
 
  IF Not EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RolePermission_Permission_PermissionId]') AND parent_object_id = OBJECT_ID(N'[dbo].[RolePermission]'))
  ALTER TABLE [dbo].[RolePermission]  WITH CHECK ADD  CONSTRAINT [FK_RolePermission_Permission_PermissionId] FOREIGN KEY([PermissionId])	REFERENCES [dbo].[Permission] ([Id])

  ---------LeaveType----------------------
GO

SET IDENTITY_INSERT [dbo].[LeaveType] ON
INSERT INTO [dbo].[LeaveType] 
([Id], [Title], [ShortName], [CreatedBy], [CreatedOn], [ModifiedBy], [ModifiedOn], [IsDeleted]) 
VALUES 
(1, 'Casual Leave', 'CL', 'admin', GETDATE(), NULL, NULL, 0),
(2, 'Earned Leave', 'EL', 'admin', GETDATE(), NULL, NULL, 0),
(3, 'Bereavement Leave', 'BL', 'admin', GETDATE(), NULL, NULL, 0),
(4, 'Parental Leave', 'ML', 'admin', GETDATE(), NULL, NULL, 0),
(5, 'Advance Leave', 'AL', 'admin', GETDATE(), NULL, NULL, 0),
(6, 'Leave in Bucket', 'LB', 'admin', GETDATE(), NULL, NULL, 0),
(7, 'Loss Of Pay', 'LOP','admin',GETDATE(),NULL, NULL,0)
SET IDENTITY_INSERT [dbo].[LeaveType] OFF

GO
 ---------------------AssetCondition---------------------------
TRUNCATE TABLE [dbo].[AssetCondition];
INSERT INTO [dbo].[AssetCondition] ([Id], [Status], [CreatedBy], [CreatedOn])
VALUES 
    (1, 'Ok', 'Admin', GETUTCDATE()),
    (2, 'Damage', 'Admin', GETUTCDATE()),
    (3, 'Missing', 'Admin', GETUTCDATE());



UPDATE ED
SET ED.TimeDoctorUserId = updates.TimeDoctorId, IsManualAttendance = 0
FROM EmploymentDetail ED
JOIN (
    VALUES 
('aadarsh.ajmera@programmers.io', 'Z4dU9lIUt2wh1-7w'),
('aakash.soni@programmers.io', 'YkNmDhPHfTHl8xIr'),
('aaryan.pancholi@programmers.io', 'Z3t0h_YV_l9er-tD'),
('aasheesh.singh@programmers.io', 'ZFyPQjrHUg8UL6ry'),
('aashish.singhal@programmers.io', 'YkNjhhPHfXVj8wI-'),
('abdul.khan@programmers.io', 'Z4iW9uzUpg2fXrpV'),
('abhay.tiwari@programmers.io', 'YpHJ9QaL7vQI3vGY'),
('abhigyan.tiwary@programmers.io', 'YkNmUxPHfXZp8xNA'),
('abhilash.joseph@programmers.io', 'YgOoUtcINx2LUeUI'),
('abhinesh.kumar@programmers.io', 'ZFiS_Bhhx8IF2YCF'),
('abhiranjan.jha@programmers.io', 'YkNkZBPHfQwD8wbX'),
('abhishek.jadhav@programmers.io', 'Y5HpFXn_vQBVUv28'),
('abhishek.jangid@programmers.io', 'YkNj1RPHfWiN8wL1'),
('abhishek.kv@programmers.io', 'Y9iqC9S2fxGUnMCh'),
('abhishek.prajapat@programmers.io', 'YkNmDBPHfaZj8xIf'),
('abhishek.yadav@programmers.io', 'ZFnpjB__FZnNaVaN'),
('abhishek@programmers.io', 'YkWy9tYtK74cXxzH'),
('ac@programmers.io', 'YfQJah6-uudI6nqt'),
('adarsh.kumar@programmers.io', 'YgOoTtcINw9BUeTx'),
('adarsh.nigam@programmers.io', 'Y4RgJ9kUSVdMCbWR'),
('aditya.goyal@programmers.io', 'Z4dVCFIUt2wh1-_i'),
('aditya.rao@programmers.io', 'YkNj0xPHfc5b8wLq'),
('aditya.shekhawat@programmers.io', 'Z4dV2lIUt2wh1_qc'),
('aditya.shrivastava@programmers.io', 'YgOoU9cIN4UTUeUL'),
('agalya.c@programmers.io', 'ZcI1FvQdqn2K-uOr'),
('ahmed.sayyed@programmers.io', 'YmEFySZpKcG3Bveo'),
('aishwarya.sm@programmers.io', 'Z4d-EE42oDAwPPxQ'),
('ajay.tanwar@programmers.io', 'YkNmDRPHfRzM8xIn'),
('ajeet.kumar@programmers.io', 'YkNmKxPHfUb-8xKW'),
('ajmal.thahseen@programmers.io', 'Y-Igkshtm5ivSS6G'),
('akanksha.rajput@programmers.io', 'YkNmORPHffRX8xLD'),
('akash.bhawaskar@programmers.io', 'YkNmRhPHfQ8Z8xMF'),
('akash.kumar@programmers.io', 'ZwYoW0abrwv2o2TF'),
('akash.sharma@programmers.io', 'ZvErScVRBAxWN-wb'),
('akash.thakur@programmers.io', 'YkNmOxPHfWQE8xLK'),
('akhil.kallur@programmers.io', 'ZIa7XvPGL2F05Rj4'),
('akhila.kadudhuri@programmers.io', 'ZIGLZu0-vVRidc7X'),
('akhila.mullapudi@programmers.io', 'Zrm4aDBSvOU7AeMS'),
('akhilesh.verma@programmers.io', 'YkNlURPHfRFo8w4h'),
('akramahmad.khan@programmers.io', 'ZvqF26WL3Mnp07GY'),
('akshay.dharmik@programmers.io', 'ZtaeJh90tw5kU3RJ'),
('akshay.jariwala@programmers.io', 'YrBXdCDZvSanhgMC'),
('akshay.kudikyala@programmers.io', 'YgObHY2KT0WZ1hwz'),
('akshay.kumar@programmers.io', 'YkNjlRPHfZMD8wJ8'),
('akshay.sopori@programmers.io', 'Yv84Avj3Cs5GNIUW'),
('akshay.tak@programmers.io', 'Yvs4uN7z8PXk2oCj'),
('akshita.purohit@programmers.io', 'Y5cXOi5DYjUxVRpm'),
('al.saeed@programmers.io', 'YkNjmBPHfbFS8wKF'),
('albert.raj@programmers.io', 'YsbLDQNnMUB1vNjL'),
('alisha.ali@programmers.io', 'ZcxRr7-9wMZ9ETvq'),
('alok.kumar@programmers.io', 'ZIa7i_PGL2F05SDL'),
('amanda.cherry@programmers.io', 'Yn5dJRVYKX3BTNop'),
('amandeep@programmers.io', 'YkazK7UZYxNxloYD'),
('amar.salian@programmers.io', 'Z480FQ10VuMJ-sCp'),
('amarendra.srivastava@programmers.io', 'YkV4vTdlrT4jwf0g'),
('amey.kalekar@programmers.io', 'Yqc93fMPa3xO_3YK'),
('amit.bhatt@programmers.io', 'aGYNdTztRodZmqxj'),
('amit.kumar@programmers.io', 'aDb1nMJcfH-rqtn1'),
('amit.makhija@programmers.io', 'YkNmSxPHfTNP8xMa'),
('amit.ojha@programmers.io', 'ZR1OfBd0lIxx3Ddw'),
('amit.sharma@programmers.io', 'YkNlJhPHfTDB8wqi'),
('amit.singh@programmers.io', 'aDQKVkX8N4LQYKBF'),
('ammar.rizvi@programmers.io', 'YpRyD1tDTYTPIXqX'),
('amol.chapte@programmers.io', 'YnNd5QCkwhiuQ0SH'),
('anand.dubey@programmers.io', 'YkNjyhPHfXRL8wK8'),
('anand.laxman@programmers.io', 'YfubkVn1PoenvV-_'),
('anand.sharma@programmers.io', 'Z0lxl9OgJAGyFH6-'),
('anandu.vijayan@programmers.io', 'YgOkc42KTy_E1kLz'),
('anas.khan@programmers.io', 'YgJe7gVjiQX9Tyls'),
('anchal.jain@programmers.io', 'YwxSe1cBOAQApnqE'),
('anchal.sawarkar@programmers.io', 'Yw4Zr1cBOAQAZJfn'),
('anit.sharma@programmers.io', 'ZiYIpkhgCwG9CsCC'),
('anita.nakum@programmers.io', 'ZzSLPUeResJ0aLz6'),
('anjali.shah@programmers.io', 'Y2zsOLR3Lats0vPw'),
('anjani.vaddi@programmers.io', 'YgJqTwVjiXDDT3IG'),
('ankit.bansal@programmers.io', 'ZA6waqoII7QAxnSX'),
('ankit.bhatnagar@programmers.io', 'YkNmEBPHfe1N8xIu'),
('ankit.gangwar@programmers.io', 'Z8KXxyNIdFvyzWPQ'),
('ankit.jain@programmers.io', 'YkNmMBPHfeL48xKn'),
('ankit.patel@programmers.io', 'YkNlHhPHfQq-8wp6'),
('ankit.sharma@programmers.io', 'YkNlThPHfSJQ8w4M'),
('ankita.kanani@programmers.io', 'Zuk9fMbm_QAlBhsZ'),
('ankita.mathur@programmers.io', 'ZNR833Sg4n4lAynS'),
('anmol.chawla@programmers.io', 'Zi87ot3O2Ou8v8JE'),
('anmol.damke@programmers.io', 'aELvtF8WbIC3ace-'),
('annumeet.kaur@programmers.io', 'ZDeZSVCHqtqnhjUU'),
('anup.panda@programmers.io', 'Z_fLLPwheo4sC4YQ'),
('anurag.agrawal@programmers.io', 'Z_yusOeqS5XP3naA'),
('anurag.dhamani@programmers.io', 'YkNkRhPHfZ5O8wYt'),
('anurag.garg@programmers.io', 'YkNlLBPHfXWU8wq8'),
('anurag.khandelwal@programmers.io', 'Y1Dhesg3-8C1QVNv'),
('anurag.sharma2@programmers.io', 'YkNkZRPHffBY8wbf'),
('anurag.sharma@programmers.io', 'YkNkURPHfU-_8wZs'),
('anvesha.singh@programmers.io', 'YgJe6wVjiTbWTylf'),
('aparna.singh@programmers.io', 'Zw44epRe3DoiRl11'),
('apeksha.dhage@programmers.io', 'Z_fA343MgTxgI4I2'),
('apoorv.varshney@programmers.io', 'YxWIi5yZcLILjKPL'),
('aravind.g@programmers.io', 'Y9iqUNS2fxGUnNB0'),
('aravind.kumar@programmers.io', 'YgOkdI2KT1JV1kL3'),
('aravind.prakash@programmers.io', 'Yrk-TUXzkN9FCIaW'),
('archana.kulkarni@programmers.io', 'Zy4QKpGNlClw4gsd'),
('arjun.choudhary@programmers.io', 'Z4dV_VIUt2wh1_v9'),
('arpit.verma@programmers.io', 'ZqtHWiFOt6szpYQs'),
('arshaa.varun@programmers.io', 'Y_xICbSD_-1CiG7m'),
('aruljothi.parthiban@programmers.io', 'aGPXSj0QNnlKRYgv'),
('arun.chacko@programmers.io', 'ZFs34-PhlkZAD3uK'),
('arun.kumar@programmers.io', 'YkNkXhPHfR3l8waw'),
('arvindh.ganesan@programmers.io', 'Z02kBsxfty5sHlFB'),
('ashok.jangir@programmers.io', 'YkNlNBPHfYsG8wrr'),
('ashwini.kumar@programmers.io', 'YgOoVtcIN14tUeUd'),
('aswathy.kanakamma@programmers.io', 'ZE9Ezvt8UAsEzCEC'),
('atul.sharma@programmers.io', 'YfpQ-Ku5YSj5t3ic'),
('avadhoot.nitave@programmers.io', 'YgOoTNcINypsUeTq'),
('avinash.kumar@programmers.io', 'Yfj728kMgSXbaF5O'),
('avishek.ray@programmers.io', 'YkNlFxPHfUNb8wpV'),
('ayush.goyal@programmers.io', 'YkV5NTdlrSH7wgAI'),
('ayush.negi@programmers.io', 'ZcxS6b-9wMZ9EU6G'),
('ayushi.ahuja@programmers.io', 'Z4dWmlIUt2wh2AUi'),
('ayushi.khandelwal@programmers.io', 'Y0zs6Ss_8yuNWkXL'),
('azhar.uddin@programmers.io', 'ZeB0UQRAxtDziXLk'),
('bahadur.bista@programmers.io', 'ZvEM5dfc8SxYRd_A'),
('balaji.anbalagan@programmers.io', 'Z7wdiICF0-AerR9h'),
('balaraju.killi@programmers.io', 'YgJqNQVjiahOT3Go'),
('balasubramanian.krishnamurthy@programmers.io', 'ZJkucMpRlw_ng0TQ'),
('bharti.saini@programmers.io', 'Y2nuVaJfeEw-anu8'),
('bhaskar.munukuri@programmers.io', 'Z_e9243MgTxgI1Xg'),
('bhavishya.shankar@programmers.io', 'ZhjtwsrliLgpIS-h'),
('bhavit.jain@programmers.io', 'Y4m9ySpNEjIMAbMG'),
('bhawna.daswani@programmers.io', 'YylOZDSBIuzHZGfs'),
('bhima.merad@programmers.io', 'aEMFwHIzRkiakx9s'),
('bhupendra.kushwaha@programmers.io', 'Z62PPYVHhnGAK7nR'),
('bhuvan@programmers.io', 'ZcXMln1HcACBRiYw'),
('bikash.das@programmers.io', 'Z_NpTvt5i6AXu-xt'),
('bindu.kasera@programmers.io', 'YkNmABPHfdrf8xHs'),
('brajendra.sharma@programmers.io', 'ZpTKT4SuAlx4QU-Z'),
('brajkishor.pal@programmers.io', 'YnNdpgCkwhiuQzcU'),
('chandan.krishna@programmers.io', 'YgObJI2KTzH51hxR'),
('chandan.mahodi@programmers.io', 'YkNlMxPHfUTr8wrn'),
('chandan.manna@programmers.io', 'YkNlLRPHfTVZ8wrE'),
('chandra.kumar@programmers.io', 'ZhaEQYeFfR9sMFIG'),
('chandra.yogesh@programmers.io', 'Zjxvt0oxqtQJQTDT'),
('channabasava.h@programmers.io', 'Z9fnpOvckYDH9hl3'),
('chanti.babu@programmers.io', 'ZKgHEX2Epe0hVdza'),
('chirag.doshi@programmers.io', 'YkW61prJ1IqU-nbl'),
('chirag.shahani@programmers.io', 'YkNmYBPHfSse8xOG'),
('chitra.singh@programmers.io', 'YkNj0BPHfWGC8wLg'),
('dada.bachute@programmers.io', 'YkNmChPHfUyG8xIW'),
('dakshita.sharma@programmers.io', 'Z4dVGlIUt2wh1_CS'),
('damini.lakhara@programmers.io', 'ZtVTkYhXxKKS5Bza'),
('darshita.sharma@programmers.io', 'Z4dVK1IUt2wh1_F6'),
('deepak.kumar@programmers.io', 'ZEYRJAayZXSdm-Sf'),
('deepak.mandal@programmers.io', 'YkNkURPHfX-Y8wZv'),
('deepak.mangal@programmers.io', 'Yun-EA1VPzUFW4fM'),
('deepak.manjare@programmers.io', 'ZN8Dzztv_ehsHkQA'),
('deepak.sharma@programmers.io', 'YkNkTBPHfTrF8wZT'),
('deepak.singh@programmers.io', 'Z8rKV5mE1tt8gb0A'),
('deepali.sanap@programmers.io', 'YqCdYVr70b6dPh_w'),
('deependra.panwar@programmers.io', 'YoX3UjNrcQQjcQUS'),
('deependra.tomer@programmers.io', 'YkNmYxPHfYKX8xOV'),
('deepika.kalwar@programmers.io', 'YoHpJ6F1nzMGYgTR'),
('deepjyoti.khatoniar@programmers.io', 'Z4pceRneBe2YlUjL'),
('dev.tekwani@programmers.io', 'Z3t0F_YV_l9er-Yb'),
('devendra.kumawat@programmers.io', 'ZIq1oz3JxlX18SuY'),
('devendra.rathore@programmers.io', 'YgOoYNcIN_CfUeVQ'),
('devendra.singh@programmers.io', 'ZiYNc0hgCwG9Cv9G'),
('devendra.surjan@programmers.io', 'ZTiu6nxnBsLDbKfQ'),
('dhankhar@programmers.io', 'Z01yfYwwkKTEm1sO'),
('dhanraj.lakhara@programmers.io', 'ZVry8VGW8FUEwmaW'),
('dharmendra.singh@programmers.io', 'YgJqgQVjiVrcT3Jg'),
('dharshan.hv@programmers.io', 'YxBql_hzI5fRBGql'),
('dhawal.gupta@programmers.io', 'aFqhipkhdKDm7vXK'),
('dheeraj.tanwar@programmers.io', 'ZcxStL-9wMZ9EUtz'),
('dhileep.ambati@programmers.io', 'YgJqOwVjiQrXT3G-'),
('dhinesh.babu@programmers.io', 'aFQWdHE2NYt7LDe0'),
('dhirender.kumar@programmers.io', 'YtfaFMm4yKNnKyKc'),
('dikshant.mathur@programmers.io', 'Y48yv_XvSjvRxajh'),
('dinesh.kaira@programmers.io', 'YgJe7QVjiZhFTylo'),
('dinesh.kumar@programmers.io', 'Z0RhJRVgZJscScgf'),
('dinesh.varma@programmers.io', 'YpSHTX2l5NpQcqFD'),
('dishant.sharma@programmers.io', 'YkbyhyrhdnkUy2d1'),
('divya.bala@programmers.io', 'YkNlUhPHfbQf8w4l'),
('divyanshu.sharma@programmers.io', 'Z6mV20raVK74EnQp'),
('durgesh.choudhary@programmers.io', 'ZIa7N_PGL2F05RaA'),
('ekta.srivastava@programmers.io', 'YgJe6AVjiUfvTylR'),
('freeda.merlin@programmers.io', 'ZA6ykqoII7QAxsp7'),
('gagan.singh@programmers.io', 'ZSYsENGufDQhZQax'),
('gajendra.singh@programmers.io', 'ZoJJIJszSjGwqXCT'),
('garima.kapoor@programmers.io', 'YkNlLBPHfRGA8wq_'),
('garvit.kandpal@programmers.io', 'ZDOVw6VDmKxhpJKT'),
('gaurav.kumar@programmers.io', 'Zyhyhb1--w7dk2YO'),
('gaurav.limba@programmers.io', 'YkNmNhPHfVdz8xK5'),
('gaurav.mone@programmers.io', 'ZxX1oY4W6jsValtq'),
('gaurav.nagar@programmers.io', 'ZqtF5SFOt6szpXgJ'),
('gautam.agarwal@programmers.io', 'YkNkYBPHfUrD8wa_'),
('gautam.moradiya@programmers.io', 'aDQKc-fpoF69CNFb'),
('geethanjali.yandamuri@programmers.io', 'Z_Tkjc-SOHiUJmM8'),
('gokulakrishnan.r@programmers.io', 'Zmb0qlhDVHnkHaf7'),
('gopal.sharma@programmers.io', 'YsPZDRmIABzD3scs'),
('gopinath.thorat@programmers.io', 'ZqeCqvHbjNlyZTjb'),
('gourisankar.sahu@programmers.io', 'YgOoVdcIN8m2UeUa'),
('goutam.chouhan@programmers.io', 'ZGHs-JFcPo8mHkYp'),
('govind.gupta@programmers.io', 'YfkjmLfk9xfPktRM'),
('gowthaman.p@programmers.io', 'Zmqc56UC4LK35juH'),
('greeshma.vincent@programmers.io', 'aGfFiQqgQDiHpVZv'),
('gunjan.agnani@programmers.io', 'Z39hcTczC0AiRnUg'),
('gunjan.gupta@programmers.io', 'YkNkSBPHfdaS8wY5'),
('gurpreet.singh@programmers.io', 'aC3gLze1AaFQJoTW'),
('harendra.singh@programmers.io', 'YkNj0BPHfRxE8wLb'),
('hariom.sharma@programmers.io', 'YkNmWRPHfTIW8xNm'),
('hariom.yadav@programmers.io', 'ZCp3sqSukFhdBXdG'),
('hariram.thapa@programmers.io', 'ZuQTs7ruASZXxeVJ'),
('harsh.ashish@programmers.io', 'ZtaeJh90tw5kU3R3'),
('harsh.dubey@programmers.io', 'Z5yL4cPcj7ttjK3O'),
('harsh.jain@programmers.io', 'Z4dUtVIUt2wh1-uk'),
('harsh.sahu@programmers.io', 'ZqtJJyFOt6szpZDf'),
('harshit.choudhary@programmers.io', 'ZOL1QK7wn2ByzHlf'),
('harshit.khandelwal@programmers.io', 'YkNlHxPHfXwG8wp9'),
('harshit.mishra@programmers.io', 'ZmarsDBDrLcm2-7R'),
('harshita.singh@programmers.io', 'YkWv0dYtK_9zXwrJ'),
('hatim.zakir@programmers.io', 'YkNmRRPHfa498xMB'),
('heather.laird@programmers.io', 'ZD0n2MP9A28soR6g'),
('hem.kumar@programmers.io', 'Y43r-bA0n6WMCsEK'),
('hemangi.bosamia@programmers.io', 'YsJzMLb_-4ptAItI'),
('hemant.kumar@programmers.io', 'Y4cIIYuE0g4plQ6H'),
('hemant.sharma@programmers.io', 'YkNmQxPHfXkn8xL1'),
('hemendra.kumawat@programmers.io', 'Z4dVnFIUt2wh1_fc'),
('hilal.ahmad@programmers.io', 'ZR0UqA-3NlgrKozi'),
('himali.prajapati@programmers.io', 'ZoJJZJszSjGwqXVW'),
('himani.rawal@programmers.io', 'Z3t-2vesMV1pRkZd'),
('himanshu.gehlot@programmers.io', 'YpRxz1tDTYTPIVUz'),
('himanshu.jain@programmers.io', 'YkNlTRPHfTEq8w4F'),
('himanshu.rathore@programmers.io', 'ZqtGYyFOt6szpXxH'),
('himanshu.singh@programmers.io', 'ZTDZeGqUS-FQqL_u'),
('hitesh.soni@programmers.io', 'YkNj1xPHfcXk8wMA'),
('hitesh.tailor@programmers.io', 'YkW-LZrJ1Mv--oeo'),
('horit.patro@programmers.io', 'Z43ggvgZR-8hpfUN'),
('isha.pandit@programmers.io', 'ZhY6Rcg9M8KEpT5V'),
('ishita.tandon@programmers.io', 'Z_kImc_WHyRRgeia'),
('ismael.ansari@programmers.io', 'YkNmKRPHfYDD8xKO'),
('jagdish.mistry@programmers.io', 'YgOoUNcIN_2hUeT-'),
('jai.gupta@programmers.io', 'YkNkQRPHfQFq8wYW'),
('jai.meena@programmers.io', 'YkNkRBPHfb098wYm'),
('jalla.venkata@programmers.io', 'aELRBGb58ASurQtq'),
('jaya.gokhlani@programmers.io', 'Z4dWN1IUt2wh1__9'),
('jayant.gawali@programmers.io', 'Z1rtnSKoYyJBF-Wp'),
('jaydeep.desai@programmers.io', 'ZCp3k6SukFhdBXOW'),
('jayesh.idnani@programmers.io', 'Ykb-P9El-HaYZl3u'),
('jayesh.tandel@programmers.io', 'YgJqRwVjiW9GT3Hl'),
('jeevanandhini.muthusamy@programmers.io', 'ZlRUQXqchktYCPaP'),
('jesse.castillon@programmers.io', 'aGS8B3nNd4xlSuUY'),
('jessica.matt@programmers.io', 'aCIZgwBZRDRn74qv'),
('jiju.thomas@programmers.io', 'Ymj95ejV6OKxmM_8'),
('jitendra.kumar01@programmers.io', 'Yrk-IUXzkN9FCGs5'),
('jitendra.kumar@programmers.io', 'YkNmJhPHfdu-8xKE'),
('jitendra.rajput@programmers.io', 'YkNmMRPHfZT18xKq'),
('joel.fernandes@programmers.io', 'YxBAZb32IfXVQdZZ'),
('joshua.nadar@programmers.io', 'Y-neqQfBIy5TvwvQ'),
('jyoti.sharma2@programmers.io', 'ZkHPfKanz_pSqNCn'),
('jyoti.sharma@programmers.io', 'YkNjyxPHfYJX8wLB'),
('kailash.dohare@programmers.io', 'YkNkYBPHfYPP8wa8'),
('kalpana.sharma@programmers.io', 'aEaRj_yyL1f3XcG1'),
('kamal.dasila@programmers.io', 'Yt6RS4Da9M0oqjFI'),
('kamlesh.bhadane@programmers.io', 'Z_fL2Pwheo4sC47L'),
('kamleshkumar.patel@programmers.io', 'Z-Zwg4dSzbLlAuLs'),
('kanak.bera@programmers.io', 'YgOoWNcIN0dGUeUo'),
('kanika.agrawal@programmers.io', 'YgJe5gVjidKBTylN'),
('kapil.agarwal@programmers.io', 'YkNj2BPHfXo98wMF'),
('kapil.gupta@programmers.io', 'YkbcrTK1XJrkDxiz'),
('kapil.patel@programmers.io', 'ZBfx1y1_7uLxBLEc'),
('karan.chaturvedi@programmers.io', 'ZQvagzLxGywC0bPK'),
('karan.goyal@programmers.io', 'YkNlKxPHfcMD8wq5'),
('karan.kacha@programmers.io', 'YkNmWxPHfSas8xNu'),
('karan.lekhwani@programmers.io', 'aCrNR91WmZJskcdE'),
('karan.messi@programmers.io', 'YkNlMhPHfS_G8wrg'),
('karishma.malviya@programmers.io', 'YlWPLC0nYNSi5NWb'),
('karishma.naula@programmers.io', 'YkNmXBPHfRfw8xNz'),
('karthick.s@programmers.io', 'ZoKcqTGpWdPVBMwi'),
('kartik.parihar@programmers.io', 'ZcxSer-9wMZ9EUgb'),
('kartik.sihoria@programmers.io', 'YkV1zTTEmf781nID'),
('kashish.appujani@programmers.io', 'Z4dVQlIUt2wh1_KV'),
('kaushal.kumar@programmers.io', 'YkNjlhPHfbkB8wJ_'),
('kavyal.jani@programmers.io', 'Z4THlh0qUB9RjuFj'),
('kd@programmers.io', 'YgJvv0kxIfqtSFzm'),
('keerthy.margana@programmers.io', 'Z8VKGGoIViMF-PaC'),
('keshav.mundra@programmers.io', 'YkNkRhPHfaxy8wYy'),
('khushi.wadhwa@programmers.io', 'YsPr0TFyZVjfrrnA'),
('kiran.singh@programmers.io', 'Z3zxlRWeYGs7YLQZ'),
('kishore.kumar@programmers.io', 'YkWdQ09WwGydPtYO'),
('krishan.kumawat@programmers.io', 'Zyhxu71--w7dk10v'),
('krishankumar.singh@programmers.io', 'Z-KepqEHY1DJIeem'),
('krishnendu.barman@programmers.io', 'aCGukCHR3NCzzJLi'),
('kritika.maheshwari@programmers.io', 'ZufBHPfiLpfX4G6p'),
('krushn.kumar@programmers.io', 'YzbyxxQAOXIpJswX'),
('kruti.gandhi@programmers.io', 'Zv-C5nrDMIQm7i2M'),
('kuldeep.choudhary@programmers.io', 'ZoJfBgttn1pzms-6'),
('kuldeep.kaushik@programmers.io', 'YkNlSRPHfbkQ8w3u'),
('kumarabhishek.anurag@programmers.io', 'ZpS_GoSuAlx4QOBK'),
('lakhan.gupta@programmers.io', 'Z3t0M_YV_l9er-b6'),
('lavanya.p@programmers.io', 'Z_fBKo3MgTxgI4iE'),
('lavanya.ravva@programmers.io', 'Yns9pYMJsVBi_DbY'),
('lavanya.sivakumar@programmers.io', 'ZLEV7A6UsCx-OUUR'),
('leela.kandimalla@programmers.io', 'aC3P2kbRHBiAzYre'),
('lewellyn.monsingh@programmers.io', 'ZFCp9sO3aQOlVA4h'),
('loganathan.mahalingam@programmers.io', 'YkNmGBPHfVR48xJH'),
('lokesh.rai@programmers.io', 'Zu08UJZUqKB-Vz9S'),
('lokitha.mukka@programmers.io', 'Z0b2E7uvQY47bkXv'),
('loveneet.kumar@programmers.io', 'ZyHVBWSzoCp3pe5r'),
('madhuker.reddy@programmers.io', 'aEGbsmQxZcoXnN6b'),
('mahak.shrimal@programmers.io', 'ZjygW3YGXp9-vTo0'),
('mahaveer.jangid1@programmers.io', 'aF04K218WPs7xkRX'),
('mahendra.kushwah@programmers.io', 'YfkO2bvopQwLJxFn'),
('mahendra.sharma@programmers.io', 'YkNlJBPHfZ3d8wqR'),
('mahesh.deshmukh@programmers.io', 'ZEYRnQayZXSdm--W'),
('mahesh.jaiswal@programmers.io', 'YsRWkJXzuGmIHoe4'),
('mahesh.jangid@programmers.io', 'Y1Dhkcg3-8C1QVo3'),
('mahipal.rathore@programmers.io', 'YzFDr53XiBh6XSzO'),
('mallika.jha@programmers.io', 'ZrXDRXrHEVvE-yQZ'),
('manav.tripathi@programmers.io', 'YvNqiyy-VA_WJLTB'),
('maneesh.bavana@programmers.io', 'aEAwFLrA2BQsOx3R'),
('manideep.gunta@programmers.io', 'ZFiTIBhhx8IF2YMS'),
('manish.chauhan@programmers.io', 'YkWcNF-51F6dloZY'),
('manish.gupta@programmers.io', 'YkqbsTSStC8isrBS'),
('manish.kaushik@programmers.io', 'aEfn8ucvwTo6IjSL'),
('manish.mishra@programmers.io', 'ZwzEIIj4UDAuG_5d'),
('manjeet.kadyan@programmers.io', 'Z0lyN9OgJAGyFIZV'),
('manju.lakshmanan@programmers.io', 'ZmcRpDXzPsWtuso9'),
('manjusri.pandhi@programmers.io', 'Z_e_JY3MgTxgI2g0'),
('manoj.chirumamilla@programmers.io', 'ZFNDlcov-SXUcst7'),
('manoj.datt@programmers.io', 'Yk69YKwFWhnVQlMO'),
('manoj.rawat@programmers.io', 'aC3QF0bRHBiAzY3g'),
('matt.price@programmers.io', 'aByqOgxyER6VqvBX'),
('mayank.pancholi@programmers.io', 'Zt6VsR6PMMxyqls_'),
('mayank.saxena@programmers.io', 'ZhTZGJk1piKzBuwU'),
('mayur.ghadge@programmers.io', 'Y8j_Dw75Z0vb6WiH'),
('mayuri.singhal@programmers.io', 'YkNmRxPHfTd98xMJ'),
('medin.ebenezer@programmers.io', 'Y9dedIzJVScBvqmV'),
('megha.mathur@programmers.io', 'ZhOIaQvuIudXJQdJ'),
('megha.parihar@programmers.io', 'Y5G6T8fHsTdd0q9m'),
('meghna.awasthi@programmers.io', 'ZGsBNansjCuCoso-'),
('meghna.goel@programmers.io', 'aA9T-gDfbgWC2_lK'),
('mitali.bajaj@programmers.io', 'YkNmHRPHfZJC8xJd'),
('mitesh.santhakumar@programmers.io', 'YgOoTdcIN3EdUeTt'),
('mitul.navapara@programmers.io', 'Z3vYePpdZamzZrwW'),
('mohammed.hussain@programmers.io', 'YkNkTxPHfe8y8wZl'),
('mohammed.siddique@programmers.io', 'ZLUqvvHtFohl-hCM'),
('mohan.prasad@programmers.io', 'Z_ZhkUIHNnXctLpW'),
('mohan.vankudoth@programmers.io', 'Zzw0TJo7urBuTTZu'),
('mohit.jain@programmers.io', 'Zo0lxFQukvU25znp'),
('mohit.kachhwaha@programmers.io', 'YkNlMBPHfQzS8wrU'),
('mohit.saini@programmers.io', 'Y7u_zLawbiO-BImd'),
('monika.rajput@programmers.io', 'aADcbAC1LN97GV_S'),
('monish.kanna@programmers.io', 'Z-eFRizBW27UMoy1'),
('mounish.maganti@programmers.io', 'aBRoNtaw5Ojvd4Ad'),
('mukesh.jangid@programmers.io', 'YkNmTxPHfbGA8xMt'),
('mukesh.kumar@programmers.io', 'YkqazTSStEzVsqeU'),
('munumonika.dhal@programmers.io', 'ZjnyILPiH0QR3exl'),
('murali.babu@programmers.io', 'YnNeJACkwhiuQ2TN'),
('nagendra.rao@programmers.io', 'Z-0qjNQuJqy09RVO'),
('naitik.shastri@programmers.io', 'YkNkTBPHfTH88wZO'),
('nanigopal.rana@programmers.io', 'YkqcPDSStBqAsrFv'),
('narendra.panwar@programmers.io', 'Z4SzU9WjNiQnqwVK'),
('naresh.somepalli@programmers.io', 'ZI_6bBEy9KMk3pb4'),
('navaroji.muralitharan@programmers.io', 'ZBfxqS1_7uLxBKlx'),
('naveen.gehlot@programmers.io', 'YpRx6ltDTYTPIWcS'),
('naveen.gopagoni@programmers.io', 'Z34kfS6d31ywvsb_'),
('naveen.patapanchala@programmers.io', 'YzPjhlVD90Mc765q'),
('naveen.potnuru@programmers.io', 'ZICmvMlGSc4-SWd5'),
('navneet.sharma@programmers.io', 'ZUoUXDnP7WtVrDd2'),
('nayeem.pasha@programmers.io', 'YgJqSgVjiVG0T3Hy'),
('neeraj.patel@programmers.io', 'Z3t0SvYV_l9er-fi'),
('neethu.haridasan@programmers.io', 'aGOq_TUu-Of_0DMD'),
('neeti.bhandari@programmers.io', 'Za4ELQIyf-o0FP0v'),
('neha.kothari@programmers.io', 'ZuwjEzAcZrd3R_a2'),
('nidhi.joshi@programmers.io', 'Y9deq4zJVScBvrO9'),
('nidhi.mishra@programmers.io', 'YhYcG6CLYOFDZ7B1'),
('nidhi.sharma@programmers.io', 'YkNlJBPHfRGH8wqU'),
('nikhil.dhannarapu@programmers.io', 'Z_fBgY3MgTxgI43j'),
('nikhil.gehlot@programmers.io', 'YkNlNxPHfcfk8wr3'),
('nikhil.lodhari@programmers.io', 'Zp48o1yj8l9vCGub'),
('nikhil.mourya@programmers.io', 'aCHEr1mrB8b5XZtE'),
('nikhilesh.gautam@programmers.io', 'Z4dVVFIUt2wh1_RQ'),
('nilesh.malviya@programmers.io', 'Y_XWuysdgbPLYpVy'),
('niranjan.kumar@programmers.io', 'Y9degozJVScBvq2O'),
('nirav.patel@programmers.io', 'Z-VqMrRRXp3pqGMn'),
('nirmal@programmers.io', 'YfkEzNoNvTz-WZKn'),
('nisha.bhatia@programmers.io', 'YlQpHMtZ-RgYQhsb'),
('nishant.kumar@programmers.io', 'YkNlGxPHfdjq8wpo'),
('nitin.kanwar@programmers.io', 'YkNjixPHfW6a8wJV'),
('nitin.sharma@programmers.io', 'YkNlNhPHfUr88wr0'),
('nitish.paliwal@programmers.io', 'ZCp3lKSukFhdBXPq'),
('nitish.tyagi@programmers.io', 'ZfRMa14JZ_cijBIF'),
('niyanta.bhatt@programmers.io', 'Zh9zhbn6RLXdj2f_'),
('nooruddin.jehangir@programmers.io', 'YkNkUBPHfTWb8wZo'),
('nupur.pal@programmers.io', 'ZdwmKMvUcKOy3exh'),
('omprakash.bijarniya@programmers.io', 'aE-_eJ4Jaw0AV9Ou'),
('onkar.lokhande@programmers.io', 'Yrk-DkXzkN9FCGZE'),
('owen.rowader@programmers.io', 'aEmh04WgNryAhS_M'),
('palak.sharma@programmers.io', 'ZxYVjf9uPr0-RbID'),
('pankaj.d@programmers.io', 'Y8F9TFwVFrv0l7tZ'),
('pankaj.jalora@programmers.io', 'YkNlQBPHfZXy8wsh'),
('partha.konda@programmers.io', 'Z_yjVSzhg9MSmZqA'),
('payal.pradhan@programmers.io', 'YgJqRQVjiQzeT3Hi'),
('payel.arora@programmers.io', 'Yr1Fh_xrt8WOZWQ4'),
('phanikumar.puppala@programmers.io', 'Z--4IMxjl-o7CtJR'),
('piyush.gajwani@programmers.io', 'YkNkXRPHfWXQ8war'),
('piyush.kumar@programmers.io', 'Zma0FsOsA-82bj_a'),
('piyush@programmers.io', 'YkWnGk9WwIPRPwJc'),
('plaban.dash@programmers.io', 'ZkMUAupsjcTrnpO-'),
('pooja.pande@programmers.io', 'Yk1a4SiP-AvoxE31'),
('pooja.pareek@programmers.io', 'YkNl_xPHfXBQ8xHk'),
('pooja.rathore@programmers.io', 'YrALBs38-KiL1QwD'),
('poonam.soni@programmers.io', 'YgJs-kkxIau-SFtI'),
('poorvi@programmers.io', 'aCQuMLaEpUUGTQiE'),
('prabuddha.mane@programmers.io', 'Z6oftImc77mxSkSz'),
('prachi.tripathi@programmers.io', 'Yv9ZzysQLAoTW77v'),
('prachi.vyas@programmers.io', 'YkNlMBPHfUps8wrX'),
('pradeep.jangid@programmers.io', 'YkNkVxPHffZ68waJ'),
('pradeep.reddy@programmers.io', 'YgJqQAVjibM8T3HL'),
('pradip.aher@programmers.io', 'aGuGy_6kCpfZL88o'),
('prajeesh.krishnan@programmers.io', 'Y5rT2isPHc7RYfWR'),
('pramod.kushwaha@programmers.io', 'YgJqPAVjiTZHT3HD'),
('pranav.gour@programmers.io', 'ZzIhtTqfcoJ7Snm_'),
('pranav.joshi@programmers.io', 'YnkJNq0qIPTn_gtV'),
('pranchan.biswas@programmers.io', 'aBxWmp9CZ1w84B0N'),
('prashant.saini2@programmers.io', 'aCre56OJFicdn4p3'),
('prashant.shukla@programmers.io', 'Y4RB3lNaT6b45EYI'),
('prateek.anand@programmers.io', 'YkNlLxPHfTL28wrR'),
('prateek.saini@programmers.io', 'ZA6yyKoII7QAxtg-'),
('prathyusha.illa@programmers.io', 'YgJs_0kxIcGZSFtR'),
('pratik.atodaria@programmers.io', 'Y8ozZZh_82leBbLi'),
('praveen.kumar2@programmers.io', 'ZE9EiPt8UAsEzBgt'),
('praveen@programmers.io', 'YkWkik9WwJAwPvev'),
('preethi.kankanala@programmers.io', 'YgJqPgVjiVCLT3HI'),
('preety.gandhi@programmers.io', 'YkNmTRPHfSgT8xMi'),
('prince.soni@programmers.io', 'ZqtJcyFOt6szpZKM'),
('pritam.bijarniya@programmers.io', 'Z4dVi1IUt2wh1_dC'),
('pritam.naik@programmers.io', 'YkNmSBPHfS9t8xMM'),
('prithvi.rentapalli@programmers.io', 'Z5x6qjLEbaukbD7U'),
('priya.kumari@programmers.io', 'YpnCbTkQwpi42EYJ'),
('priya.narone@programmers.io', 'Z9rKIO-IwKVGrhQn'),
('priyanka.ratnam@programmers.io', 'ZTovYW_4tf5zUY0G'),
('priyanka.tiwari@programmers.io', 'ZiuNZkZfwqseK1w7'),
('priyanshu.prajapat@programmers.io', 'ZwzacghCxthldQEJ'),
('priyanshu.saraswat@programmers.io', 'Z6mVwEraVK74EnKm'),
('prudhvi.reddy@programmers.io', 'aCHjhDgP9V_xb85W'),
('puneet.gandhi@programmers.io', 'aF7WVLB6RA8Nqgim'),
('purva.goyal@programmers.io', 'YkNkWBPHfT-r8waP'),
('purvansh.jain@programmers.io', 'aGNvCadVzMgoH62m'),
('pushpender.kumar@programmers.io', 'YmJT8nEIXxDPNpKp'),
('pushpendra.kukreti@programmers.io', 'Z8VKoWoIViMF-Px3'),
('pushpendra.shekhawat@programmers.io', 'Z6mV8kraVK74EnWc'),
('pushpendra.singh@programmers.io', 'Y5wGQABGn-HEszZ3'),
('r.nikhil@programmers.io', 'YgJvw0kxISujSFzw'),
('rabindra.biswal@programmers.io', 'Z_e_f43MgTxgI22R'),
('rachuri.ashwin@programmers.io', 'YrrwjxzntxzjhMnM'),
('raghu.b@programmers.io', 'YylOhjSBIuzHZIaH'),
('raghuveer.singh@programmers.io', 'YkNjzxPHfTCT8wLY'),
('ragini.patel@programmers.io', 'ZJFiGr_Pkv9OGZ2g'),
('rahil.machchhar@programmers.io', 'Z6mqhSrHAW09L-IK'),
('rahul.karale@programmers.io', 'YkNmNBPHfTK48xKx'),
('rahul.sharma@programmers.io', 'Z4dWelIUt2wh2AOu'),
('rahul.tripathi@programmers.io', 'ZvFMs8-Xp6Qojeq-'),
('rahul@programmers.io', 'YgOoTNcIN1AsUeTm'),
('raj.gupta@programmers.io', 'ZqtK7yFOt6szpZ1y'),
('rajat.srivastava@programmers.io', 'YgJe4wVjiaIqTyk8'),
('rajendra.perala@programmers.io', 'YgJqOAVjifv2T3G1'),
('rajendra.saini@programmers.io', 'YkqbBTSStHC4squw'),
('rajesh.ganesan@programmers.io', 'ZFNt1QTLyUn1l3Ej'),
('rajesh.israni@programmers.io', 'aFTv31Ebjc9YmUpx'),
('rajesh.kumar@programmers.io', 'YkNjzRPHfdza8wLR'),
('rajesh.royal@programmers.io', 'YzqHYU8p_OyTwiY8'),
('rajesh.soni@programmers.io', 'YgJvvUkxIQWMSFzf'),
('rajkumar.kompelli@programmers.io', 'Z_fLl_wheo4sC4tj'),
('rajswee.surana@programmers.io', 'ZVMBUZ4sPrapcGs6'),
('raju.sivaprasad@programmers.io', 'Z-u0sF2oFR6W5-pz'),
('rajveer.saini@programmers.io', 'YkNjiRPHfQyU8wJP'),
('rajvi.sanghvi@programmers.io', 'YgOkcY2KTzJO1kLw'),
('rakesh.chaubey@programmers.io', 'YgJqNAVjicGKT3Gk'),
('rakesh.verma@programmers.io', 'ZK1xz6cNRCUcMobQ'),
('rakshitha.jakkam@programmers.io', 'YyquNj4-S4XgX-96'),
('raman.sharma@programmers.io', 'YkNmXRPHfYOT8xN6'),
('raman.tanwar@programmers.io', 'Y7vaoOPNYEcHvZyV'),
('ramavtar.sharma@programmers.io', 'YkWwIs5W7Zv6jH4r'),
('ramesh.jadala@programmers.io', 'Z_fKt_wheo4sC3-v'),
('ramprabhu.ts@programmers.io', 'YgJqOgVjiSV1T3G6'),
('ranabir.mal@programmers.io', 'ZX_olJ-TJS_uWV9y'),
('randeep.borpatra@programmers.io', 'YkNmFRPHfaQN8xI7'),
('ranjan@programmers.io', 'YgOoStcIN2aDUeTf'),
('ranjeet.singh@programmers.io', 'YkqbwjSStK1RsrCv'),
('rashmi.ks@programmers.io', 'Zhy621_fgFu6oiMo'),
('rashmi.pal@programmers.io', 'Z5CtKEzkxAtkDKQG'),
('ravi.jangid@programmers.io', 'ZqtFWiFOt6szpXQL'),
('ravi.nidamarthi@programmers.io', 'YgJqQwVjiUdMT3HZ'),
('ravi.porwal@programmers.io', 'YgOoVNcINyseUeUP'),
('ravi.raniwal@programmers.io', 'Zy3S9t2SaIsSM5n4'),
('ravi.singh@programmers.io', 'YzFD_Z3XiBh6XUTo'),
('ravikiran.chandana@programmers.io', 'YgOoYNcIN-AYUeVM'),
('ravikiran.raju@programmers.io', 'Z_e-3I3MgTxgI2RO'),
('ravindra.rathore@programmers.io', 'ZoY4jTcFn6_LrIS9'),
('ravisankar.pandian@programmers.io', 'ZJkuispRlw_ng0X-'),
('ravitej.pragnapuram@programmers.io', 'aD7Kqz07nXq_yQbb'),
('reenu.adlakha@programmers.io', 'YkNjzBPHfSAB8wLL'),
('reuben.abraham@programmers.io', 'Z5sYP2WvIbymnQKm'),
('ria.chaturvedi@programmers.io', 'YgUWptcIN1oeWpfz'),
('richa.bhargava@programmers.io', 'YkNjkRPHfRui8wJu'),
('riddhi.sharma@programmers.io', 'YkNlKRPHfbvQ8wqy'),
('ridhima.khandelwal@programmers.io', 'YkNmTBPHfRRX8xMd'),
('rimjhim.patodiya@programmers.io', 'YkNlGRPHfUKu8wpe'),
('rishab.kaushik@programmers.io', 'YkNmAxPHfQSe8xH1'),
('rishabh.mahla@programmers.io', 'Y4hylJiY9BE_qEVV'),
('rishabh.sankhla@programmers.io', 'Z4SzktWjNiQnqwg4'),
('rishi.dharedi@programmers.io', 'YkNmYRPHfWhW8xOK'),
('rituraj.bhadauria@programmers.io', 'YpCEdcifS8JXKOoE'),
('rituraj.rajawat@programmers.io', 'ZqtG-SFOt6szpYFG'),
('robin.chhipa@programmers.io', 'Y-nHr8DpAl6a0bh7'),
('rohan.sethi@programmers.io', 'YpnnhNQ9dL6bJnel'),
('rohini.alagarsamy@programmers.io', 'YkNmKhPHfQ0c8xKR'),
('rohit.jain@programmers.io', 'Z6mVqEraVK74EnFo'),
('rohit.kumar@programmers.io', 'Z3_RBTQFliMHzPLX'),
('rohit.pal@programmers.io', 'ZtaeJh90tw5kU3QY'),
('rokesh.aluru@programmers.io', 'YqGv9TzSQ0RiPcKm'),
('roop.saini@programmers.io', 'Z4dUzlIUt2wh1-0H'),
('ruchi.madhwani@programmers.io', 'YkNmGxPHfeln8xJV'),
('ruchi.sharma@programmers.io', 'ZqtFnyFOt6szpXYu'),
('ruchika.bhatia@programmers.io', 'YkNmPxPHfe6s8xLe'),
('ruchika.nagda@programmers.io', 'YqrVX50Ht6AqZ4E0'),
('ruchin.khanna@programmers.io', 'ZfqQeFbCnGShaKqz'),
('rupesh.kadiveti@programmers.io', 'ZU48IOEA85SnhZ_v'),
('rushiraj.bedage@programmers.io', 'ZCp3XKSukFhdBW0I'),
('sabarish.p@programmers.io', 'YkNlVBPHfbuA8w4t'),
('sachin.jangid@programmers.io', 'YkNjlBPHfSWv8wJ4'),
('sachin.malik@programmers.io', 'YqNHqLfTkv1hCwKI'),
('sachin.sisodiya@programmers.io', 'ZPClGNR0U5lLcJBQ'),
('sagar.mutha@programmers.io', 'YgOoV9cIN-EjUeUi'),
('sagar.saxena@programmers.io', 'YkNjkxPHfTJn8wJ0'),
('sahil.bhusari@programmers.io', 'Z4dWJFIUt2wh1_63'),
('sai.srujan@programmers.io', 'Z_ynteeqS5XP3h5V'),
('saikiran.reddy@programmers.io', 'ZxuKZ2Mrby-uEU-W'),
('saikumar.golla@programmers.io', 'ZrMju8kQe0lS9A3n'),
('sairam.nampally@programmers.io', 'ZDOVuKVDmKxhpJCo'),
('sakshi.malviya@programmers.io', 'ZHmM8BV_CY53526u'),
('sakshi.ojha@programmers.io', 'ZrB7GKRHOzfquN4X'),
('saloni.nallulwar@programmers.io', 'ZsSNiE9OGTRGNvEm'),
('samik.chatterjee@programmers.io', 'ZufxR2hp7HHlNFMV'),
('sanchita.kini@programmers.io', 'YkNmWBPHfRe_8xNf'),
('sandeep.gupta@programmers.io', 'YkNmIxPHfVYH8xJ6'),
('sandeep.kumar@programmers.io', 'ZCuyQNpPWtbOsgnA'),
('sandeep.soni@programmers.io', 'YkNj0RPHfeB38wLj'),
('sandhya.subudhi@programmers.io', 'YgJtAUkxIaBcSFtX'),
('sangeetha.das@programmers.io', 'ZCp3k6SukFhdBXOm'),
('sanjana.modi@programmers.io', 'Z_87_F84lkoKsJBv'),
('sanjay.chouhan@programmers.io', 'ZmaJdSAdPhDVTZRc'),
('sanjay.rajpurohit@programmers.io', 'Z43oafgZR-8hpk96'),
('sanket.pokale@programmers.io', 'Y5gPmixPwXkHHLbP'),
('sanskar.sharma@programmers.io', 'Z4dWE1IUt2wh1_3q'),
('santhosh.appusamy@programmers.io', 'YkNmURPHfUdv8xM5'),
('santosh.patil@programmers.io', 'ZbeIF5re37FgiOEj'),
('sarada.pennabadi@programmers.io', 'aFQcA3E2NYt7LH9h'),
('saritha.martha@programmers.io', 'Y4nWZtD77n4UNx6_'),
('saritha.t@programmers.io', 'YgJqMwVjiQHaT3Gf'),
('sarthak.gupta@programmers.io', 'Y70so6WzxhbxZJS8'),
('sarvesh.barnwal@programmers.io', 'Y7fxG9yGg3ytEiYz'),
('sasikumar.rajasekaran@programmers.io', 'ZJkuicpRlw_ng0Xk'),
('satendra.kumar@programmers.io', 'ZegFI_Bk08Cakpnr'),
('satish.kadali@programmers.io', 'aEw930DeV4rTXS0Z'),
('satish.manwar@programmers.io', 'YgOoT9cIN1tXUeT2'),
('satishkumar.mungi@programmers.io', 'Z9fYhqxwPEZFaZpo'),
('satya.mandal@programmers.io', 'Z_e0FWtAQGgQdhN8'),
('satyabrat.sabat@programmers.io', 'ZMiawV6wAhV4PFYy'),
('satyabrata.mohanty@programmers.io', 'YgJvwEkxIYFFSFzq'),
('satyanarayan.kukkala@programmers.io', 'ZflkhacsaapJm0Sz'),
('saumya.arora@programmers.io', 'Y5G6FMfHsTdd0qOO'),
('saundarya.barik@programmers.io', 'Z8_sOirpC22IwUUh'),
('saurabh.agarwal@programmers.io', 'YkNj1BPHff-H8wLy'),
('saurabh.desai@programmers.io', 'YpXLpGKIRwOxdoSS'),
('saurabh.kumawat@programmers.io', 'YkNjgxPHfWJ78wIt'),
('saurabh.shelar@programmers.io', 'YkNmSBPHff-28xMP'),
('sayam.chopra@programmers.io', 'ZzMoV9YlmLBQYq1G'),
('sayed.hashmi@programmers.io', 'Zr9bA30BkC2OoVWU'),
('shagun.mangal@programmers.io', 'Z4dVeVIUt2wh1_a2'),
('shahrukh.anwar@programmers.io', 'ZrHi4s3dfh6O70_Z'),
('shaik.allabakshu@programmers.io', 'ZAV_HVx-E20r4yIr'),
('shailendra.chourey@programmers.io', 'ZdSzkwX9e86f6mGa'),
('shakti.singh2@programmers.io', 'YgOoWtcIN5M4UeUz'),
('shanmugam.kannan@programmers.io', 'Z8hmYo922qWR-vKs'),
('shantiswaroop.mamillapalli@programmers.io', 'ZvE045zsG-FxHqor'),
('sharath.kumar@programmers.io', 'YgJqSwVjibtLT3H6'),
('shashank.agrawal@programmers.io', 'ZCp3lKSukFhdBXPQ'),
('shashank.tripathi@programmers.io', 'ZzMbCXxgVg_AjRvO'),
('shavi.sharma@programmers.io', 'aAZVJ2eEbC4z98Wh'),
('sheetal.chouhan@programmers.io', 'Y6wfqZMPJ4hXMYsG'),
('shefali.goyal@programmers.io', 'Zlm-6UwuJkzVlRqg'),
('shefali.saxena@programmers.io', 'Zh_L-lcUl8zZm16W'),
('shekhawat.dharmendra@programmers.io', 'Z3aWj9gJWkGd-4od'),
('shikha.soni@programmers.io', 'YkNmTRPHfVBR8xMl'),
('shikhar.srivastava@programmers.io', 'Z7wFoq7bIedP7Y5o'),
('shinu.george@programmers.io', 'YkNjjBPHfX1k8wJZ'),
('shiv.sharma@programmers.io', 'Z86QqbMuaVj8qvYf'),
('shiva.sunkari@programmers.io', 'Y7u_t7awbiO-BH3u'),
('shivaji.bhosale@programmers.io', 'ZVt-o_vA5fZwWn7p'),
('shivam.chakrapani@programmers.io', 'YkNlNRPHfUdm8wru'),
('shivam.chouhan@programmers.io', 'ZwTmnPN6yOpiwHsS'),
('shivam.garg@programmers.io', 'Z0lx8NOgJAGyFIMo'),
('shivam.gaurav@programmers.io', 'Zswj1_AYr5_mj9ux'),
('shivam.mishra@programmers.io', 'Z6BvVLktP6KMUih1'),
('shivsundar.bankar@programmers.io', 'Y75jyCn-msiGADWl'),
('shobhit.gupta@programmers.io', 'Yuoey3-UjfqR6OWL'),
('shomi.biswas@programmers.io', 'YkNkZRPHfWfV8wbc'),
('shouvik.biswas@programmers.io', 'YpRyAltDTYTPIXQa'),
('shraddha.verma@programmers.io', 'Y8Fgn1Sa-Pk9fop_'),
('shradha.pavshere@programmers.io', 'YgOoVdcINxAZUeUT'),
('shravan.ravva@programmers.io', 'ZyhyDr1--w7dk2GF'),
('shreya.wadhwani@programmers.io', 'YgOoXdcINxjLUeVC'),
('shubham.paliwal@programmers.io', 'Z6BmcLktP6KMUcpG'),
('shubham.saraswat@programmers.io', 'Z3t0ZfYV_l9er-mi'),
('shubhangi.jain@programmers.io', 'ZKaJyyBycRI2X8L9'),
('shubhangi.kamthe@programmers.io', 'YkbcTTK1XCpWDxTa'),
('shubhra.dubey@programmers.io', 'Z1boHdB8JsWs7j_J'),
('siddharth.sharma@programmers.io', 'YkNmPRPHfSid8xLT'),
('siddheshwar.tupe@programmers.io', 'Y_XW1CsdgbPLYqQj'),
('simon.ayyamperumal@programmers.io', 'aCrfAaOJFicdn4tz'),
('sindy.davis@programmers.io', 'aGS7rXnNd4xlSuKB'),
('siva.nalla@programmers.io', 'YpnCXDkQwpi42D2n'),
('siva.sathyam@programmers.io', 'Z-vrj3WO5Wm5BDhn'),
('skylar.claypool@programmers.io', 'Y9vNLcTwEn6ZMMfE'),
('sneha.aggarwal@programmers.io', 'ZiZtHvxcIgCdYp6W'),
('somnath.pujari@programmers.io', 'YkNmSRPHfW2H8xMU'),
('sonali.sulake@programmers.io', 'Y47_rWQpHLt_EbEs'),
('sonia.mehta@programmers.io', 'Z9LhiAnEvmjvO7KM'),
('sonika.tyagi@programmers.io', 'ZKzwJSBupM4kpXlu'),
('sovan.kapuria@programmers.io', 'ZDzPr-F6v20ma8QF'),
('spandana.karuka@programmers.io', 'aC3QF0bRHBiAzY39'),
('srichand.jakka@programmers.io', 'ZqtLRSFOt6szpaBJ'),
('srinath.k@programmers.io', 'YgJe6gVjiXrETylW'),
('srinivas.chari@programmers.io', 'ZEZ_qoQp3CTpOGjP'),
('srinivasa.gannamaneni@programmers.io', 'ZmasfjA6Ta-dUd_Z'),
('sriram.balaji@programmers.io', 'YkNmQBPHfVYT8xLi'),
('ssabatini@ecisolutions.com', 'YwYiWZGam3h6-DWF'),
('stephen.jeyaraj@programmers.io', 'Y1oRh-Z1Lq6YPuZy'),
('sudarshan.gajdhane@programmers.io', 'YkNmShPHfXO28xMX'),
('sudha.bonthu@programmers.io', 'YtZuFnhCL17ggrqt'),
('sudhanshu.joshi@programmers.io', 'YkNlGRPHfRpi8wpb'),
('sudhir.kumar@programmers.io', 'YlAbIZRS9E39DDRk'),
('sujatha.kinnera@programmers.io', 'ZAV-5lx-E20r4xzU'),
('sujeet.yadav@programmers.io', 'Z_jZm4gFYJl08Acg'),
('sukhdev.singh@programmers.io', 'ZsiJuf0I-rneOu5P'),
('sumant.kumar@programmers.io', 'YkNlUBPHfZ_X8w4Z'),
('sumanth.reddy@programmers.io', 'Y1D3Uj8POeqnfELw'),
('sumer.parmar@programmers.io', 'Y4m92ypNEjIMAbYI'),
('sumit.darak@programmers.io', 'YkNmZRPHffOH8xOc'),
('sumit.kashyap@programmers.io', 'YkNmLRPHfZpp8xKf'),
('sundar.selvaraj@programmers.io', 'Y2IOiqszozyWE586'),
('sunita.chougale@programmers.io', 'Z08Bao9T8rtpMonU'),
('sunny.jha@programmers.io', 'YqnJYuSh2GdchDMz'),
('supriya.dhole@programmers.io', 'ZNR8v3Sg4n4lAyjA'),
('suraj.pancholi@programmers.io', 'YkWbr1-51CbEloHd'),
('suraj.surendran@programmers.io', 'ZU4N7OrdC1xUA746'),
('surbhi.bagul@programmers.io', 'Z3tsZvYV_l9er2sX'),
('surbhi.shukla@programmers.io', 'ZAlppwycsHXTdcoA'),
('surender.ummareddy@programmers.io', 'ZoJKQpszSjGwqYGI'),
('suresh.gaddam@programmers.io', 'Zgpcyve2R5JJM5Hg'),
('suresh.naik@programmers.io', 'YkNmWhPHfUzU8xNq'),
('suresh.sen@programmers.io', 'YkNkZxPHfVwC8wbn'),
('surya.siram@programmers.io', 'aGT2wSYFcoACqAeL'),
('suryakant.sahoo@programmers.io', 'YwxSZFcBOAQApmij'),
('sushant.shastri@programmers.io', 'YwNMtZCHYUCvK3tG'),
('suvidha.durairaj@programmers.io', 'ZoTs0EFNIEZiNe8D'),
('swapnil.sharma@programmers.io', 'YkNjkBPHfbme8wJp'),
('swati.mathur@programmers.io', 'Z857tBv4_asHDR6b'),
('taher@programmers.io', 'Y2oivyz4tkg64mJn'),
('tammy.chatten@programmers.io', 'aF9k_09QHWdpvBII'),
('tanisha.khunteta@programmers.io', 'Y483VFRSdkupHHG6'),
('tanisha.srivastava@programmers.io', 'YgJe6wVjiRJpTylc'),
('tanoy.pandit@programmers.io', 'Ymf5ck_UjHjpHzYy'),
('tanya.agarwal@programmers.io', 'YkNlKRPHffWn8wqv'),
('tanya.singh@programmers.io', 'ZNxjGz-19qr4XEhs'),
('tapan.gupta@programmers.io', 'ZVr4gFGW8FUEwpye'),
('tara.goyal@programmers.io', 'YkNlThPHfXQf8w4S'),
('tarun.saini@programmers.io', 'YkNl_RPHfURf8xHW'),
('tathagat.dalai@programmers.io', 'YkNmQxPHfQh_8xLx'),
('tej.rathore@programmers.io', 'YkNlSBPHfYVH8w3U'),
('thati.krishna@programmers.io', 'YgJqTQVjiQ7CT3IC'),
('thiyagarajan.venkatesan@programmers.io', 'ZKJwoCyzMimBN8t2'),
('truptida.panigrahi@programmers.io', 'Z5jhkbT1TrwAFmsf'),
('tushar.garg@programmers.io', 'YfkAaXyGxphPvJrp'),
('tushar.kumar@programmers.io', 'YkNkYhPHfbN28wbH'),
('udaya.pragada@programmers.io', 'ZIa7JPPGL2F05RWx'),
('uma.maheswari@programmers.io', 'Z8Afxixit5IcAM-x'),
('uppala.narendra@programmers.io', 'Z2AXREEN2uym4dUs'),
('vaibhav.arya@programmers.io', 'Z4dWSFIUt2wh2AFx'),
('vaibhav.mengawade@programmers.io', 'YgOoS9cIN0jvUeTi'),
('vaibhav.nawale@programmers.io', 'Y5qyEWogPEtWsf3o'),
('vaibhav.padsala@programmers.io', 'Z30rMbGksbZf_SDw'),
('vaibhav.singh@programmers.io', 'aDb1_sJcfH-rqt4Y'),
('vaishali.kapoor@programmers.io', 'ZBQy2THgP0tTZOdj'),
('vaishali.kataria@programmers.io', 'YkNlPRPHfewk8wsU'),
('vamsi.krishna2@programmers.io', 'ZF4FwepTBMG32QmX'),
('vamsi.krishna@programmers.io', 'YgOkcI2KT_aq1kLt'),
('vamsi.manukonda@programmers.io', 'ZUM9U_rruvyJD2rQ'),
('vanam.venkatesh@programmers.io', 'YgJqTAVjiTVmT3H_'),
('vanoor.basha@programmers.io', 'YgJqRAVjiWt0T3Hd'),
('vanshika.sahni@programmers.io', 'YpnoJdQ9dL6bJr1j'),
('varalakshmi.devi@programmers.io', 'ZrB9g6RHOzfquPUS'),
('vartika.srivastava@programmers.io', 'ZlAuc14ybmom6CWq'),
('varun.kasimkota@programmers.io', 'YgOkdo2KT4bs1kL9'),
('vasantha.raj@programmers.io', 'YkNmCRPHfadU8xIT'),
('venkata.pavan@programmers.io', 'YgJs_kkxIQFDSFtO'),
('venkateswar.battula@programmers.io', 'ZPWKlwuUVVTHbWZh'),
('venkatraj.dudyala@programmers.io', 'Z_e-eY3MgTxgI17N'),
('vibhor.mathpal@programmers.io', 'ZpTDt4SuAlx4QQnL'),
('vicky.agarwal@programmers.io', 'YgOoX9cINxHFUeVJ'),
('vijendra.yadav@programmers.io', 'ZmaP3r-RGh0Qj5gn'),
('vikas.kumar@programmers.io', 'YkNkQhPHfUGG8wYb'),
('vikas.singh@programmers.io', 'YkNlORPHfYcg8wsB'),
('vikas.soni@programmers.io', 'YkNkXxPHfWff8wa5'),
('vikas.sonwal@programmers.io', 'YkNlPxPHfSMy8wse'),
('vikash.mishra@programmers.io', 'YkNlGhPHfQRa8wpk'),
('vimalan.vinayagam@programmers.io', 'Z8VJWWoIViMF-PAX'),
('vimla.babaria@programmers.io', 'ZOzAnr_BTN2ub8ZD'),
('vimlesh.jangid@programmers.io', 'YkqbTDSStAHgsqwe'),
('vinay.mundada@programmers.io', 'YgObI42KT1un1hxO'),
('vinay.thote@programmers.io', 'ZDzV4a6gDGT7sTIJ'),
('vinisha.rathod@programmers.io', 'Z0lyIdOgJAGyFIVo'),
('vinit.nagal@programmers.io', 'Z9fMy3t5KixJhHJc'),
('vinod.kumar@programmers.io', 'YkNjhRPHfZrk8wI7'),
('vinod.tailor@programmers.io', 'YlPNSEiB6YRJ7sn-'),
('vinodhini.thiruvalluvar@programmers.io', 'Z9wMOBG-tQWtrCPd'),
('vipin.sharma@programmers.io', 'Y7fDm5NKj8xTXKE4'),
('vipin.verma@programmers.io', 'Y2Dm7z70IDh6UeMR'),
('vipul.kumar@programmers.io', 'YkNj1hPHfX-c8wL8'),
('virag.sharma@programmers.io', 'YkNlIBPHfRKw8wqA'),
('viresh.johri@programmers.io', 'Zx8hJBT9QTF86BSQ'),
('vishal.bhalothia@programmers.io', 'YwnAwDszC6jYNkq_'),
('vishal.kumar@programmers.io', 'Z01zwIwwkKTEm2bx'),
('vishal.middha@programmers.io', 'Y9pOJNcrMCZUbmow'),
('vishal.pareek@programmers.io', 'Yfj728kMgah2aF5P'),
('vishal.sharma@programmers.io', 'ZQGzpXhFla_bGYwD'),
('vishal.upadhyay@programmers.io', 'ZZOrPmqr1xO4AgPl'),
('vishal.vyas@programmers.io', 'Z_fWBbR0VCOLhdF4'),
('vishwas.kalaskar@programmers.io', 'YgOoXNcIN7A-UeU-'),
('vivek.nigam@programmers.io', 'Zx9CVCFW4UA0Jj1f'),
('vivek.pal@programmers.io', 'Z35I6xTnne_-uC8o'),
('vivek.panwar@programmers.io', 'ZqtHnyFOt6szpYaE'),
('vivek.sharma@programmers.io', 'YkNmFBPHfe4p8xI3'),
('xarai.courter@programmers.io', 'ZsXP1va1Nzbu6bc2'),
('y.samuel@programmers.io', 'YkNmVhPHfYR58xNR'),
('yashvardhan.soni@programmers.io', 'Z4S-UtWjNiQnq4ld'),
('yashveer.shakya@programmers.io', 'YkNmIRPHfRfL8xJs'),
('yashwant.kag@programmers.io', 'YkNlMxPHfTn28wrk'),
('yogesh.gautam@programmers.io', 'YpnCfTkQwpi42E2P'),
('yogesh.gawande@programmers.io', 'YgOoWtcIN3gXUeU2'),
('yogesh.jaiman@programmers.io', 'YkNlOxPHfck_8wsK'),
('yogesh.sharma@programmers.io', 'aC3PbkbRHBiAzYay'),
('yogita.keswani@programmers.io', 'Y5LgOw6qaX_mlJtS'),
('yogita.ozarde@programmers.io', 'ZzrmJlcfQirXaoL7'),
('yugal.sharma@programmers.io', 'YkqbGTSStIPHsqvW'),
('yuvraj.sharma@programmers.io', 'Z0lyAdOgJAGyFIQk')
) AS updates(Email, TimeDoctorId)
ON LOWER(ED.Email) = LOWER(updates.Email);